// http://hl7.org/fhir/us/core/2017Jan/valuesets.html
// https://www.hl7.org/fhir/valueset-vaccine-code.html


var vaccineCodes = [
    {"code": "01", "display": "DTP"},
    {"code": "02", "display": "OPV"},
    {"code": "03", "display": "MMR"},
    {"code": "04", "display": "M/R"},
    {"code": "05", "display": "measles"},
    {"code": "06", "display": "rubella"},
    {"code": "07", "display": "mumps"},
    {"code": "08", "display": "Hep B, adolescent or pediatric"},
    {"code": "09", "display": "Td (adult), adsorbed"},
    {"code": "10", "display": "IPV"},
    {"code": "100", "display": "pneumococcal conjugate PCV 7"},
    {"code": "101", "display": "typhoid, ViCPs"},
    {"code": "102", "display": "DTaP/DTP-Hib-Hep B"},
    {"code": "103", "display": "meningococcal C conjugate"},
    {"code": "104", "display": "Hep A-Hep B"},
    {"code": "105", "display": "vaccinia (smallpox) diluted"},
    {"code": "106", "display": "DTaP, 5 pertussis antigens"},
    {"code": "107", "display": "DTaP, unspecified formulation"},
    {"code": "108", "display": "meningococcal, unspecified formulation"},
    {"code": "109", "display": "pneumococcal, unspecified formulation"},
    {"code": "11", "display": "pertussis"},
    {"code": "110", "display": "DTaP-Hep B-IPV"},
    {"code": "111", "display": "influenza, live, intranasal"},
    {"code": "112", "display": "tetanus toxoid, unspecified formulation"},
    {"code": "113", "display": "Td (adult) preservative free"},
    {"code": "114", "display": "meningococcal MCV4P"},
    {"code": "115", "display": "Tdap"},
    {"code": "116", "display": "rotavirus, pentavalent"},
    {"code": "117", "display": "VZIG (IND)"},
    {"code": "118", "display": "HPV, bivalent"},
    {"code": "119", "display": "rotavirus, monovalent"},
    {"code": "12", "display": "diphtheria antitoxin"},
    {"code": "120", "display": "DTaP-Hib-IPV"},
    {"code": "121", "display": "zoster"},
    {"code": "122", "display": "rotavirus, unspecified formulation"},
    {"code": "123", "display": "influenza, H5N1-1203"},
    {"code": "125", "display": "Novel Influenza-H1N1-09, nasal"},
    {"code": "126", "display": "Novel influenza-H1N1-09, preservative-free"},
    {"code": "127", "display": "Novel influenza-H1N1-09"},
    {"code": "128", "display": "Novel Influenza-H1N1-09, all formulations"},
    {"code": "129", "display": "Japanese Encephalitis, unspecified formulation"},
    {"code": "13", "display": "TIG"},
    {"code": "130", "display": "DTaP-IPV"},
    {"code": "131", "display": "typhus, historical"},
    {"code": "132", "display": "DTaP-IPV-HIB-HEP B, historical"},
    {"code": "133", "display": "Pneumococcal conjugate PCV 13"},
    {"code": "134", "display": "Japanese Encephalitis IM"},
    {"code": "135", "display": "Influenza, high dose seasonal"},
    {"code": "136", "display": "Meningococcal MCV4O"},
    {"code": "137", "display": "HPV, unspecified formulation"},
    {"code": "138", "display": "Td (adult)"},
    {"code": "139", "display": "Td(adult) unspecified formulation"},
    {"code": "14", "display": "IG, unspecified formulation"},
    {"code": "140", "display": "Influenza, seasonal, injectable, preservative free"},
    {"code": "141", "display": "Influenza, seasonal, injectable"},
    {"code": "142", "display": "tetanus toxoid, not adsorbed"},
    {"code": "143", "display": "Adenovirus types 4 and 7"},
    {"code": "144", "display": "influenza, seasonal, intradermal, preservative free"},
    {"code": "145", "display": "RSV-MAb (new)"},
    {"code": "146", "display": "DTaP,IPV,Hib,HepB"},
    {"code": "147", "display": "meningococcal MCV4, unspecified formulation"},
    {"code": "148", "display": "Meningococcal C/Y-HIB PRP"},
    {"code": "149", "display": "influenza, live, intranasal, quadrivalent"},
    {"code": "15", "display": "influenza, split (incl. purified surface antigen)"},
    {"code": "150", "display": "influenza, injectable, quadrivalent, preservative free"},
    {"code": "151", "display": "influenza nasal, unspecified formulation"},
    {"code": "152", "display": "Pneumococcal Conjugate, unspecified formulation"},
    {"code": "153", "display": "Influenza, injectable, MDCK, preservative free"},
    {"code": "154", "display": "Hep A, IG"},
    {"code": "155", "display": "influenza, recombinant, injectable, preservative free"},
    {"code": "156", "display": "Rho(D)-IG"},
    {"code": "157", "display": "Rho(D) -IG IM"},
    {"code": "158", "display": "influenza, injectable, quadrivalent"},
    {"code": "159", "display": "Rho(D) - Unspecified formulation"},
    {"code": "16", "display": "influenza, whole"},
    {"code": "160", "display": "Influenza A monovalent (H5N1), ADJUVANTED-2013"},
    {"code": "161", "display": "Influenza, injectable,quadrivalent, preservative free, pediatric"},
    {"code": "162", "display": "meningococcal B, recombinant"},
    {"code": "163", "display": "meningococcal B, OMV"},
    {"code": "164", "display": "meningococcal B, unspecified"},
    {"code": "17", "display": "Hib, unspecified formulation"},
    {"code": "18", "display": "rabies, intramuscular injection"},
    {"code": "19", "display": "BCG"},
    {"code": "20", "display": "DTaP"},
    {"code": "21", "display": "varicella"},
    {"code": "22", "display": "DTP-Hib"},
    {"code": "23", "display": "plague"},
    {"code": "24", "display": "anthrax"},
    {"code": "25", "display": "typhoid, oral"},
    {"code": "26", "display": "cholera"},
    {"code": "27", "display": "botulinum antitoxin"},
    {"code": "28", "display": "DT (pediatric)"},
    {"code": "29", "display": "CMVIG"},
    {"code": "30", "display": "HBIG"},
    {"code": "31", "display": "Hep A, pediatric, unspecified formulation"},
    {"code": "32", "display": "meningococcal MPSV4"},
    {"code": "33", "display": "pneumococcal polysaccharide PPV23"},
    {"code": "34", "display": "RIG"},
    {"code": "35", "display": "tetanus toxoid, adsorbed"},
    {"code": "36", "display": "VZIG"},
    {"code": "37", "display": "yellow fever"},
    {"code": "38", "display": "rubella/mumps"},
    {"code": "39", "display": "Japanese encephalitis SC"},
    {"code": "40", "display": "rabies, intradermal injection"},
    {"code": "41", "display": "typhoid, parenteral"},
    {"code": "42", "display": "Hep B, adolescent/high risk infant"},
    {"code": "43", "display": "Hep B, adult"},
    {"code": "44", "display": "Hep B, dialysis"},
    {"code": "45", "display": "Hep B, unspecified formulation"},
    {"code": "46", "display": "Hib (PRP-D)"},
    {"code": "47", "display": "Hib (HbOC)"},
    {"code": "48", "display": "Hib (PRP-T)"},
    {"code": "49", "display": "Hib (PRP-OMP)"},
    {"code": "50", "display": "DTaP-Hib"},
    {"code": "51", "display": "Hib-Hep B"},
    {"code": "52", "display": "Hep A, adult"},
    {"code": "53", "display": "typhoid, parenteral, AKD (U.S. military)"},
    {"code": "54", "display": "adenovirus, type 4"},
    {"code": "55", "display": "adenovirus, type 7"},
    {"code": "56", "display": "dengue fever"},
    {"code": "57", "display": "hantavirus"},
    {"code": "58", "display": "Hep C"},
    {"code": "59", "display": "Hep E"},
    {"code": "60", "display": "herpes simplex 2"},
    {"code": "61", "display": "HIV"},
    {"code": "62", "display": "HPV, quadrivalent"},
    {"code": "63", "display": "Junin virus"},
    {"code": "64", "display": "leishmaniasis"},
    {"code": "65", "display": "leprosy"},
    {"code": "66", "display": "Lyme disease"},
    {"code": "67", "display": "malaria"},
    {"code": "68", "display": "melanoma"},
    {"code": "69", "display": "parainfluenza-3"},
    {"code": "70", "display": "Q fever"},
    {"code": "71", "display": "RSV-IGIV"},
    {"code": "72", "display": "rheumatic fever"},
    {"code": "73", "display": "Rift Valley fever"},
    {"code": "74", "display": "rotavirus, tetravalent"},
    {"code": "75", "display": "vaccinia (smallpox)"},
    {"code": "76", "display": "Staphylococcus bacterio lysate"},
    {"code": "77", "display": "tick-borne encephalitis"},
    {"code": "78", "display": "tularemia vaccine"},
    {"code": "79", "display": "vaccinia immune globulin"},
    {"code": "80", "display": "VEE, live"},
    {"code": "801", "display": "AS03 Adjuvant"},
    {"code": "81", "display": "VEE, inactivated"},
    {"code": "82", "display": "adenovirus, unspecified formulation"},
    {"code": "83", "display": "Hep A, ped/adol, 2 dose"},
    {"code": "84", "display": "Hep A, ped/adol, 3 dose"},
    {"code": "85", "display": "Hep A, unspecified formulation"},
    {"code": "86", "display": "IG"},
    {"code": "87", "display": "IGIV"},
    {"code": "88", "display": "influenza, unspecified formulation"},
    {"code": "89", "display": "polio, unspecified formulation"},
    {"code": "90", "display": "rabies, unspecified formulation"},
    {"code": "91", "display": "typhoid, unspecified formulation"},
    {"code": "92", "display": "VEE, unspecified formulation"},
    {"code": "93", "display": "RSV-MAb"},
    {"code": "94", "display": "MMRV"},
    {"code": "95", "display": "TST-OT tine test"},
    {"code": "96", "display": "TST-PPD intradermal"},
    {"code": "97", "display": "TST-PPD tine test"},
    {"code": "98", "display": "TST, unspecified formulation"},
    {"code": "99", "display": "RESERVED - do not use"},
    {"code": "998", "display": "no vaccine administered"},
    {"code": "999", "display": "unknown"},
    {"code": "AGRPAL", "display": "Agrippal"},
    {"code": "AVAXM", "display": "Avaxim"},
    {"code": "BCG", "display": "BCG"},
    {"code": "CDT", "display": "CDT"},
    {"code": "CMX", "display": "COMVAX"},
    {"code": "DTP", "display": "Triple Antigen"},
    {"code": "DTPA", "display": "DTPa"},
    {"code": "ENGP", "display": "Engerix B"},
    {"code": "FLRIX", "display": "Fluarix"},
    {"code": "FLUVAX", "display": "Fluvax"},
    {"code": "FLVRN", "display": "Fluvirin"},
    {"code": "FVXJNR", "display": "Fluvax Junior"},
    {"code": "GNDIP", "display": "Diphtheria"},
    {"code": "GNFLU", "display": "Influenza"},
    {"code": "GNHEP", "display": "Hepatitis B"},
    {"code": "GNHIB", "display": "HIB"},
    {"code": "GNHPA", "display": "Hepatitis A"},
    {"code": "GNJEN", "display": "Japanese Encephalitis"},
    {"code": "GNMEA", "display": "Measles"},
    {"code": "GNMEN", "display": "Meningococcal C"},
    {"code": "GNMUM", "display": "Mumps"},
    {"code": "GNPNE", "display": "Pneumococcal"},
    {"code": "GNPOL", "display": "Polio"},
    {"code": "GNROX", "display": "Rotavirus"},
    {"code": "GNRUB", "display": "Rubella"},
    {"code": "GNTET", "display": "Tetanus"},
    {"code": "GNVAR", "display": "Varicella"},
    {"code": "HATWNJ", "display": "Twinrix Junior"},
    {"code": "HAVAQ", "display": "Vaqta Paed/Adol"},
    {"code": "HAVJ", "display": "Havrix Junior"},
    {"code": "HBOC", "display": "HibTITER"},
    {"code": "HBV", "display": "HBV"},
    {"code": "HBVP", "display": "HBVAX II"},
    {"code": "HBX", "display": "Hiberix"},
    {"code": "IFHX", "display": "Infanrix Hexa"},
    {"code": "IFIP", "display": "Infanrix-IPV"},
    {"code": "IFPA", "display": "Infanrix Penta"},
    {"code": "IFX", "display": "Infanrix"},
    {"code": "IFXB", "display": "InfanrixHepB"},
    {"code": "INFLUV", "display": "Influvac"},
    {"code": "IPV", "display": "IPOL"},
    {"code": "JEVAX", "display": "JE-VAX"},
    {"code": "MENJUG", "display": "Menjugate"},
    {"code": "MENTEC", "display": "Meningitec"},
    {"code": "MENUME", "display": "Menomune"},
    {"code": "MENVAX", "display": "Mencevax ACWY"},
    {"code": "MMR", "display": "MMR"},
    {"code": "MMRCSL", "display": "MMR II"},
    {"code": "MMRSKB", "display": "Priorix"},
    {"code": "MNTRX", "display": "Menitorix"},
    {"code": "NEISVC", "display": "NeisVac-C"},
    {"code": "OPV", "display": "Polio"},
    {"code": "P", "display": "Pertussis"},
    {"code": "PANVAX", "display": "Panvax"},
    {"code": "PDCL", "display": "Pediacel"},
    {"code": "PLCL", "display": "Poliacel"},
    {"code": "PNEUMO", "display": "Pneumovax"},
    {"code": "PRPD", "display": "ProHIBit"},
    {"code": "PROQAD", "display": "ProQuad"},
    {"code": "PRPOMP", "display": "PedvaxHIB"},
    {"code": "PRPT", "display": "ActHIB"},
    {"code": "PRVNR", "display": "Prevenar 7"},
    {"code": "PRVTH", "display": "Prevenar 13"},
    {"code": "PRXTEX", "display": "Priorix-Tetra"},
    {"code": "QDCL", "display": "Quadracel"},
    {"code": "ROTRIX", "display": "Rotarix"},
    {"code": "ROTTEQ", "display": "Rotateq"},
    {"code": "SYNFLX", "display": "Synflorix"},
    {"code": "TCL", "display": "Tripacel"},
    {"code": "VAXGRP", "display": "Vaxigrip"},
    {"code": "VGRJNR", "display": "Vaxigrip Junior"},
    {"code": "VLRIX", "display": "Varilrix"},
    {"code": "VRVAX", "display": "Varivax"}
];
